### ISSUE TITLE
Unable to use custom template with 0.37

### ISSUE THREAD

**Issue by stevespringett** [coveooss/json-schema-for-humans#113]
I have a custom template - based on the js template but heavily modified. 

With 0.35.x and 0.36.x, I was able to specify the path to the custom template just fine. However, with 0.37, the custom template cannot be found.

The console output is:
```
Traceback (most recent call last):
  File "/usr/local/bin/generate-schema-doc", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/json_schema_for_humans/cli.py", line 59, in main
    config = get_final_config(
  File "/usr/local/lib/python3.9/site-packages/json_schema_for_humans/generation_configuration.py", line 107, in get_final_config
    final_config = _apply_config_cli_parameters(final_config, config_parameters)
  File "/usr/local/lib/python3.9/site-packages/json_schema_for_humans/generation_configuration.py", line 157, in _apply_config_cli_parameters
    return GenerationConfiguration.from_dict(current_configuration_as_dict)  # type: ignore
  File "/usr/local/lib/python3.9/site-packages/dataclasses_json/api.py", line 82, in from_dict
    return _decode_dataclass(cls, kvs, infer_missing)
  File "/usr/local/lib/python3.9/site-packages/dataclasses_json/core.py", line 201, in _decode_dataclass
    init_kwargs[field.name] = _decode_generic(field_type,
  File "/usr/local/lib/python3.9/site-packages/dataclasses_json/core.py", line 247, in _decode_generic
    res = type_(value)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/enum.py", line 384, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/enum.py", line 702, in __new__
    raise ve_exc
ValueError: '/Users/steve/Development/MyProject/docgen/json/templates/mytemplate' is not a valid TemplateName
```

Reverting back to 0.36.1 works fine.

**Comment by dblanchette** [comment]
Hi @stevespringett, version 0.37.1 should work.

It reverts using an enum for "template_name" which I suppose would have been the issue here.

Hope this fixes it, if not don't hesitate to reopen.
