### ISSUE TITLE
ref key referencing a url invalid directory

### ISSUE THREAD

**Issue by shahzebsiddiqui** [coveooss/json-schema-for-humans#59]
I have schema files hosted in docs https://buildtesters.github.io/schemas/ i found your library interesting for autogenerating json schema docs.

It looks as if this library is validating the json schema before it generates the docs. I get this error

```
(schemas) siddiq90@DOE-7086392 schemas % generate-schema-doc script/script-v1.0.schema.json
Traceback (most recent call last):
  File "/Users/siddiq90/.local/share/virtualenvs/schemas-TS0lwyF1/bin/generate-schema-doc", line 8, in <module>
    sys.exit(main())
  File "/Users/siddiq90/.local/share/virtualenvs/schemas-TS0lwyF1/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/siddiq90/.local/share/virtualenvs/schemas-TS0lwyF1/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/siddiq90/.local/share/virtualenvs/schemas-TS0lwyF1/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/siddiq90/.local/share/virtualenvs/schemas-TS0lwyF1/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/siddiq90/.local/share/virtualenvs/schemas-TS0lwyF1/lib/python3.7/site-packages/json_schema_for_humans/generate.py", line 1071, in main
    generate_from_file_object(schema_file, result_file, config=config)
  File "/Users/siddiq90/.local/share/virtualenvs/schemas-TS0lwyF1/lib/python3.7/site-packages/json_schema_for_humans/generate.py", line 901, in generate_from_file_object
    result = generate_from_schema(schema_file, config=config)
  File "/Users/siddiq90/.local/share/virtualenvs/schemas-TS0lwyF1/lib/python3.7/site-packages/json_schema_for_humans/generate.py", line 822, in generate_from_schema
    intermediate_schema = build_intermediate_representation(schema_file, config, loaded_schemas)
  File "/Users/siddiq90/.local/share/virtualenvs/schemas-TS0lwyF1/lib/python3.7/site-packages/json_schema_for_humans/generate.py", line 495, in build_intermediate_representation
    intermediate_representation = _build_node(0, "", schema_path, [], _load_schema(schema_path, []))
  File "/Users/siddiq90/.local/share/virtualenvs/schemas-TS0lwyF1/lib/python3.7/site-packages/json_schema_for_humans/generate.py", line 474, in _build_node
    is_pattern_properties=schema_key == "patternProperties",
  File "/Users/siddiq90/.local/share/virtualenvs/schemas-TS0lwyF1/lib/python3.7/site-packages/json_schema_for_humans/generate.py", line 474, in _build_node
    is_pattern_properties=schema_key == "patternProperties",
  File "/Users/siddiq90/.local/share/virtualenvs/schemas-TS0lwyF1/lib/python3.7/site-packages/json_schema_for_humans/generate.py", line 491, in _build_node
    new_node.refers_to = _resolve_ref(new_node, schema)
  File "/Users/siddiq90/.local/share/virtualenvs/schemas-TS0lwyF1/lib/python3.7/site-packages/json_schema_for_humans/generate.py", line 369, in _resolve_ref
    _load_schema(referenced_schema_path, referenced_schema_path_to_element),
  File "/Users/siddiq90/.local/share/virtualenvs/schemas-TS0lwyF1/lib/python3.7/site-packages/json_schema_for_humans/generate.py", line 381, in _load_schema
    with open(schema_file_path, encoding="utf-8") as schema_fp:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/siddiq90/Documents/schemas/script/https:/buildtesters.github.io/schemas/global/global.schema.json'
```

This schema file https://github.com/buildtesters/schemas/blob/master/script/script-v1.0.schema.json is referencing a public url https:/buildtesters.github.io/schemas/global/global.schema.json where my schema can be fetched. The issue is in your library when you are opening the schema file you assume schema file based on `$ref` is a local path. Any way to get around this.

I was able to generate schema docs for https://github.com/buildtesters/schemas/blob/master/global/global.schema.json which doesn't have any cross reference.

**Comment by dblanchette** [comment]
Hi @shahzebsiddiqui!

I added support for references to URL. I tested it successfully with the schema you provided.

This has just been released as version 0.21.

Have a nice day :)
