### ISSUE TITLE
Markdown template producing error

### ISSUE THREAD

**Issue by virtadan** [coveooss/json-schema-for-humans#83]
I'm attempting to use the markdown template and seeing an error about calling `name_for_breadcrumbs` on a list on line 311 of `json_schema_for_humans/md_template.py`.

**Version:** 0.32.0

Here is the command I'm running as well as the stacktrace

```
generate-schema-doc --config template_name=md report.json
```

```
Traceback (most recent call last):
  File "/usr/local/bin/generate-schema-doc", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/json_schema_for_humans/generate.py", line 262, in main
    generate_from_file_object(schema_file, result_file, config=config)
  File "/usr/local/lib/python3.9/site-packages/json_schema_for_humans/generate.py", line 176, in generate_from_file_object
    result = generate_from_schema(schema_file, config=config)
  File "/usr/local/lib/python3.9/site-packages/json_schema_for_humans/generate.py", line 95, in generate_from_schema
    rendered = template.render(schema=intermediate_schema, config=config)
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 5, in top-level template code
  File "/usr/local/lib/python3.9/site-packages/json_schema_for_humans/templates/md/content.html", line 92, in top-level template code
    {% include "section_properties_details.html" %}
  File "/usr/local/lib/python3.9/site-packages/json_schema_for_humans/templates/md/section_properties_details.html", line 29, in top-level template code
    {% include "content.html" %}
  File "/usr/local/lib/python3.9/site-packages/json_schema_for_humans/templates/md/content.html", line 81, in top-level template code
    {% include "section_array.html" %}
  File "/usr/local/lib/python3.9/site-packages/json_schema_for_humans/templates/md/section_array.html", line 4, in top-level template code
    {{ schema | md_array_items_restrictions | md_generate_table }}
  File "/usr/local/lib/python3.9/site-packages/json_schema_for_humans/md_template.py", line 311, in array_items_restrictions
    item_label = item.name_for_breadcrumbs or f"Array Item {i}"
AttributeError: 'list' object has no attribute 'name_for_breadcrumbs'
```

**Comment by dblanchette** [comment]
Hi!

Please try version v0.32.1 that I just released and let me know if it fixes it!

**Comment by virtadan** [comment]
That works! Thanks for the quick response.
