### ISSUE TITLE
Unhelpful error message when providing a non-existent output directory

### ISSUE THREAD

**Issue by da1910** [coveooss/json-schema-for-humans#97]
In the process of porting a CI script to a new platform I mistakenly changed an output file so that it pointed to a non-existent directory.  This results in an error message claiming that generate-schema-docs cannot find a CSS file, it would be better ifwe either either:

1. Handle this case by creating the directory, like `mkdir -p`
2. Correctly report up-front that the output directory does not exist

I would prefer the second option, but either would be better than the current behavior. I am happy to submit a PR once a decision has been made on what, if anything, to do.

```
Traceback (most recent call last):
  File "C:\git\project\packages\python.3.7.4\tools\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\git\project\packages\python.3.7.4\tools\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\git\project\spdx-venv\Scripts\generate-schema-doc.exe\__main__.py", line 9, in <module>
  File "C:\git\project\spdx-venv\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "C:\git\project\spdx-venv\lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "C:\git\project\spdx-venv\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\git\project\spdx-venv\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "C:\git\project\spdx-venv\lib\site-packages\json_schema_for_humans\generate.py", line 258, in main
    generate_from_file_object(schema_file, result_file, config=config)
  File "C:\git\project\spdx-venv\lib\site-packages\json_schema_for_humans\generate.py", line 174, in generate_from_file_object
    copy_css_and_js_to_target(result_file.name, config)
  File "C:\git\project\spdx-venv\lib\site-packages\json_schema_for_humans\generate.py", line 199, in copy_css_and_js_to_target
    shutil.copy(source_file_path, os.path.join(target_directory, file_to_copy))
  File "C:\git\project\packages\python.3.7.4\tools\lib\shutil.py", line 248, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\git\project\packages\python.3.7.4\tools\lib\shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\git\\project/doc/schema\\schema_doc.css'
```

**Comment by dblanchette** [comment]
Hi! I'd be happy with solution number 2.
